package gateway

// stream.go: client-facing SSE plumbing for Task 12 — the flush-per-frame
// client stream with its first-byte latch (the no-reissue guard), and the
// stamp writer that adds the request context (id/model/created) to frames
// generated by zen.TranslateResponsesStream, which Task 8 deferred because
// the translator has no request context of its own.

import (
	"bytes"
	"encoding/json"
	"io"
	"net/http"
)

// clientStream relays SSE frames to the client. It buffers writes until a
// complete frame (terminated by a blank line) is available, then writes the
// frame and flushes — one flush per frame, so a slow client can never stall
// the whole relay behind a partial frame.
//
// The status line and headers stay unwritten until the first frame is
// ready: this keeps the "errors before first byte → OpenAI error envelope"
// contract possible even for a 2xx upstream whose stream dies before its
// first frame. started (the first-byte latch) is the no-reissue guard: once
// true, the handler must never re-issue the request — the client already
// owns committed bytes and cannot be given a second stream.
type clientStream struct {
	w       http.ResponseWriter
	flusher http.Flusher // nil when the writer does not flush
	buf     []byte
	started bool
	frames  int
}

func newClientStream(w http.ResponseWriter) *clientStream {
	f, _ := w.(http.Flusher)
	return &clientStream{w: w, flusher: f}
}

func (s *clientStream) Write(p []byte) (int, error) {
	s.buf = append(s.buf, p...)
	for {
		end, ok := frameEnd(s.buf)
		if !ok {
			break
		}
		if err := s.emit(s.buf[:end]); err != nil {
			return len(p), err
		}
		s.buf = s.buf[:copy(s.buf, s.buf[end:])]
	}
	return len(p), nil
}

// emit commits one complete frame: headers on first use, write, flush.
func (s *clientStream) emit(frame []byte) error {
	if !s.started {
		s.started = true
		s.w.Header().Set("Content-Type", "text/event-stream")
		s.w.Header().Set("Cache-Control", "no-cache")
		s.w.WriteHeader(http.StatusOK)
	}
	if _, err := s.w.Write(frame); err != nil {
		return err
	}
	s.frames++
	if s.flusher != nil {
		s.flusher.Flush()
	}
	return nil
}

// close flushes any trailing bytes that never saw their terminating blank
// line (a clean relay always ends with a complete frame, so this is a no-op
// on success and is NOT called after a relay error).
func (s *clientStream) close() error {
	if len(s.buf) == 0 {
		return nil
	}
	tail := s.buf
	s.buf = nil
	return s.emit(tail)
}

// frameEnd returns the length of b up to and including the first blank line
// ("\n\n" or the CRLF variant "\n\r\n"). SSE data never contains a blank
// line inside a frame, so this is the frame boundary.
func frameEnd(b []byte) (int, bool) {
	best := -1
	if i := bytes.Index(b, []byte("\n\n")); i >= 0 {
		best = i + 2
	}
	if i := bytes.Index(b, []byte("\n\r\n")); i >= 0 {
		if end := i + 3; best < 0 || end < best {
			best = end
		}
	}
	if best < 0 {
		return 0, false
	}
	return best, true
}

// stampWriter injects id/model/created into every JSON data frame that
// lacks them. zen.TranslateResponsesStream emits chat.completion.chunk
// frames without request context (Task 8 deferred), so the handler — which
// knows the request model — stamps them here. Non-JSON frames and the
// [DONE] terminator pass through untouched; the usage frame keeps its
// explicit "choices":[].
//
// Like clientStream it buffers to frame granularity, so the downstream
// writer still sees one complete frame per flush.
type stampWriter struct {
	dst     io.Writer
	buf     []byte
	id      string
	model   string
	created int64
}

func newStampWriter(dst io.Writer, id, model string, created int64) *stampWriter {
	return &stampWriter{dst: dst, id: id, model: model, created: created}
}

func (s *stampWriter) Write(p []byte) (int, error) {
	s.buf = append(s.buf, p...)
	for {
		end, ok := frameEnd(s.buf)
		if !ok {
			break
		}
		if _, err := s.dst.Write(s.stamp(s.buf[:end])); err != nil {
			return len(p), err
		}
		s.buf = s.buf[:copy(s.buf, s.buf[end:])]
	}
	return len(p), nil
}

// close flushes the unframed tail (a clean relay leaves none).
func (s *stampWriter) close() error {
	if len(s.buf) == 0 {
		return nil
	}
	tail := s.buf
	s.buf = nil
	_, err := s.dst.Write(s.stamp(tail))
	return err
}

func (s *stampWriter) stamp(frame []byte) []byte {
	const prefix = "data: "
	if !bytes.HasPrefix(frame, []byte(prefix)) {
		return frame // comments, event: lines, [DONE] pass through
	}
	trimmed := bytes.TrimSuffix(bytes.TrimSuffix(frame[len(prefix):], []byte("\n")), []byte("\n"))
	var chunk map[string]any
	if err := json.Unmarshal(trimmed, &chunk); err != nil {
		return frame
	}
	if _, ok := chunk["id"]; !ok {
		chunk["id"] = s.id
	}
	if _, ok := chunk["model"]; !ok {
		chunk["model"] = s.model
	}
	if _, ok := chunk["created"]; !ok {
		chunk["created"] = s.created
	}
	out, err := json.Marshal(chunk)
	if err != nil {
		return frame
	}
	return append(append([]byte(prefix), out...), '\n', '\n')
}
